version: 2.1
orbs:

  cypress: cypress-io/cypress@1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/app

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install --frozen-lockfile

      - run: npm config set scripts-prepend-node-path true

      - save_cache:
          paths:
            - ~/.cache 
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - run: yarn lint

      - run: yarn size
      
      - run: yarn test

      - run: yarn ci:cypress-run
